config/routes.rb
Store::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registration", omniauth_callbacks: "omniauth_callbacks" } do
    get '/users/sign_out' => 'devise/sessions#destroy', :as => "destroy_user_session"

end

 

  resources :preferences

  resources :brands

  resources :likes

  resources :categories
   
  resources :users

  root to: 'static_pages#home'

  

end

app/models/preference.rb
class Preference < ActiveRecord::Base
   attr_accessible :user_id, :brand_id 

   belongs_to :user
   belongs_to :brand
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :validatable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :password, :password_confirmation, :remember_me
  attr_accessible :name, :gender, :email, :provider, :uid

  has_many :likes
  has_many :categories, through: :likes

  has_many :preferences
  has_many :brands, through: :preferences

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.email = auth.info.email
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  before_save { |user| user.email = email.downcase }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  # GET /preferences
  # GET /preferences.json
  def index
    @preferences = Preference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @preferences }
    end
  end

  # GET /preferences/1
  # GET /preferences/1.json
  def show
    @preference = Preference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @preference }
    end
  end

  # GET /preferences/new
  # GET /preferences/new.json
  def new
    @preference = Preference.new
    @brands = Brand.find(:all)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @preference }
    end
  end

  # GET /preferences/1/edit
  def edit
    @preference = Preference.find(params[:id])
  end

  # POST /preferences
  # POST /preferences.json
  def create
    @preference = Preference.new(params[:preference])
    params[:brand_ids].each do |brand|
    Preference.create(:brand_id => brand, :user_id => current_user.id)
  end
    redirect_to destroy_user_session_path
    
  end

  # PUT /preferences/1
  # PUT /preferences/1.json
  def update
    @preference = Preference.find(params[:id])

    respond_to do |format|
      if @preference.update_attributes(params[:preference])
        format.html { redirect_to @preference, notice: 'Preference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preferences/1
  # DELETE /preferences/1.json
  def destroy
    @preference = Preference.find(params[:id])
    @preference.destroy

    respond_to do |format|
      format.html { redirect_to preferences_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/views/preferences/_form.html.erb
<%= form_for(@preference) do |f| %>
  <% if @preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@preference.errors.count, "error") %> prohibited this preference from being saved:</h2>

      <ul>
      <% @preference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preferences/edit.html.erb
<h1>Editing preference</h1>

<%= render 'form' %>

<%= link_to 'Show', @preference %> |
<%= link_to 'Back', preferences_path %>

app/views/preferences/index.html.erb
<h1>Listing preferences</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @preferences.each do |preference| %>
  <tr>
    <td><%= link_to 'Show', preference %></td>
    <td><%= link_to 'Edit', edit_preference_path(preference) %></td>
    <td><%= link_to 'Destroy', preference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Preference', new_preference_path %>

app/views/preferences/new.html.erb
<%= form_for @preference do |f| %>

<div class="div2" align='center'>
	<div class="container">
		<h10 align="center" style="border-bottom:30px"> Your Favorite Brands... </h10>
	</div>
	<div class="container" align="center" style="padding-top:20px">
		<div class="row" align='center'>
			<% @brands.each do |brand| %>
			<div class="span2" align="center" style="margin-top:0px">
				<label for='brand_ids_'>
					<img src= <%= brand.image %> class="new">
				</label>
				<div><%= check_box_tag 'brand_ids[]', brand.id %></div>
			</div>
			<% end %>
		</div>
		<%= f.submit "Next!", :class => "button1", :style => "font-size:1.6em" %>
		<%= link_to 'Back', likes_path, :class => 'btn btn-mini'%>
	</div>
</div>
<% end %>

app/views/preferences/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_preference_path(@preference) %> |
<%= link_to 'Back', preferences_path %>