config/routes.rb
Store::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registration", omniauth_callbacks: "omniauth_callbacks" } do
    get '/users/sign_out' => 'devise/sessions#destroy', :as => "destroy_user_session"

end

 

  resources :preferences

  resources :brands

  resources :likes

  resources :categories
   
  resources :users

  root to: 'static_pages#home'

  

end

app/models/brand.rb
class Brand < ActiveRecord::Base
   attr_accessible :name, :gender, :image

   has_many :preferences
   has_many :users, through: :preferences
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render json: @brand, status: :created, location: @brand }
      else
        format.html { render action: "new" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
<div class="container">
<div>
<%= f.text_field :name, placeholder: 'name'  %>
</div>
<div>
<%= f.text_field :image, placeholder: 'image' %>
</div>
<div>
<%= f.text_field :gender, placeholder: 'gender' %>
</div>
</div>

  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<h1>Listing brands</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @brands.each do |brand| %>
  <tr>
    <td><%= link_to 'Show', brand %></td>
    <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
    <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>